name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - numpy=1.19.2
  - pip:
    - basicsr
    - facexlib
    - lmdb
    - pyyaml
    - scipy
    - tb-nightly
    - tqdm
    - yapf
    - albumentations==0.4.3
    - diffusers
    - opencv-python==4.1.2.30
    - opencv-python-headless
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - pynvml
    - gradio
    - keras-unet
    - fairseq
    - -e .
